name: Time artifact
on:
  push:
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Create a text file
        run: |
          echo "The time is $(date -u)" > time.txt

      - name: Upload time artifact
        uses: actions/upload-artifact@v3
        with:
          name: time-artifact # optional, default is artifact
          path: time.txt
          if-no-files-found: error # optional, default is warn
          retention-days: 1 # optional, maximum 90 days
